spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    data: data.sql
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

#  spring.jpa.generate-ddl=true
#  spring.jpa.hibernate.ddl-auto=true
#  spring.datasource.initialize=true